# Generated by Django 3.1.7 on 2021-10-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20211018_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='waiting_customer',
            field=models.ManyToManyField(blank=True, default='', null=True, to='items.WaitUser'),
        ),
    ]
