# Generated by Django 3.1.7 on 2021-09-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_orderitem_review_customer_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='altro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
