# Generated by Django 3.1.7 on 2021-09-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_order_altro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='altro',
        ),
    ]
