# Generated by Django 3.1.7 on 2021-10-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20211005_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review_single_customer_done',
            field=models.BooleanField(default=False),
        ),
    ]
