# Generated by Django 3.1.7 on 2021-10-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_order_review_single_customer_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
