# Generated by Django 3.1.7 on 2021-10-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20211011_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='waiting_customer',
        ),
        migrations.AddField(
            model_name='item',
            name='waiting_customer',
            field=models.ManyToManyField(to='items.WaitUser'),
        ),
    ]
