# Generated by Django 3.1.7 on 2021-09-14 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0003_auto_20210911_1506'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=5)),
                ('title_of_comment', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_shop', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_shop', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ReviewShop',
                'verbose_name_plural': 'ReviewShops',
            },
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_comment', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('rating', models.FloatField(default=5)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_item', to='items.item')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_item', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ReviewItem',
                'verbose_name_plural': 'ReviewItems',
            },
        ),
    ]
