# Generated by Django 3.1.7 on 2021-09-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewitem',
            name='altro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
